services:
  apache:
    image: httpd:alpine
    container_name: apache_web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/

  mysql:
    image: mysql:8.0
    container_name: medivault-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: medivault_db
      MYSQL_USER: root
      MYSQL_PASSWORD: MediVault123!
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

flask_app:
    build: .
    container_name: medivault-flask-app
    restart: always

    # Expose port 5000 so you can browse it on localhost:5000
    ports:
      - "5000:5000"

    environment:
      # Tell Flask which app to run
      FLASK_ENV: "production"
      FLASK_SECRET_KEY: "${FLASK_SECRET_KEY}"
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASSWORD: "MediVault123!"
      DB_NAME: "medivault_db"
      SQLALCHEMY_ECHO: "False"

    depends_on:
      - mysql

volumes:
  mysql_data:
