services:
  apache:
    image: httpd:alpine
    container_name: apache_web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: medivault_db
      MYSQL_USER: medivault_user
      MYSQL_PASSWORD: medivault_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
