services:
  apache:
    image: httpd:alpine
    container_name: apache_web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: medivault_db
      MYSQL_USER: root
      MYSQL_PASSWORD: MediVault123!
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  flask_app:
    build: .
    container_name: flask_app
    restart: always

    # Expose port 5000 so you can browse it on localhost:5000
    ports:
      - "5000:5000"

    environment:
      # Tell Flask which app to run
      FLASK_APP: app.py
      FLASK_ENV: development

      # This is the single DATABASE_URL var that SQLAlchemy will read.
      # Format: mysql+pymysql://<user>:<password>@<hostname>:<port>/<database>
      DATABASE_URL: mysql+pymysql://root:MediVault123!@mysql_db:3306/medivault_db

    depends_on:
      - mysql

    # Mount your code and templates into /app inside the container
    volumes:
      - ./backend/:/app
      - ./html/:/app/templates

volumes:
  mysql_data:
