version: "3.8"

services:
  # ───────────────────────────────────────────────────────────────────────
  # MySQL 5.7 service (named "db")
  # ───────────────────────────────────────────────────────────────────────
  db:
    image: mysql:5.7
    container_name: rbac_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: rbac
      MYSQL_USER: root
      MYSQL_PASSWORD: admin

    # Only one "volumes:" block—do not repeat this key twice
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/schema_script.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./Database/data_population.sql:/docker-entrypoint-initdb.d/02_data.sql

  # ───────────────────────────────────────────────────────────────────────
  # Flask + Gunicorn service
  # ───────────────────────────────────────────────────────────────────────
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rbac_flask_app
    restart: unless-stopped
    depends_on:
      - db

    ports:
      - "80:5000"

    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=Your_Very_Strong_Secret_Key_ChangeThis!
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=rbac

    # (Optional) If you want to see your local `backend/` changes without rebuilding:
    # volumes:
    #   - ./backend:/app

volumes:
  db_data:
