name: Deploy to EC2 via Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: akskmy/ssd_flask_app:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd project/compose
          git pull

          # Stop and clean up any existing containers
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker rm $(sudo docker ps -a -q) || true

          # Pull the latest image (you already pushed it above)
          sudo docker pull akskmy/ssd_flask_app:latest

          # Remove the stack
          sudo docker stack rm my_stack
          sleep 5  # wait for services to shut down

          # Remove volumes (ignore errors if not found or in use)
          sudo docker volume rm my_stack_db_data compose_db_data db_data || true

          # Ensure network exists
          sudo docker network create my_stack_app_net || true

          # Deploy stack
          sudo docker stack deploy -c docker-compose.yml --detach=false my_stack
