name: MediVault Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flask-and-ui-test:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: rbac
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image for Flask
      run: docker build -t medivault-app .

    - name: Run Flask container
      run: |
        docker run -d --name flask-app \
          --network host \
          -v ${{ github.workspace }}/backend:/app \
          -w /app \
          -e FLASK_SECRET_KEY=testsecret \
          -e FLASK_ENV=development \
          -e DB_HOST=127.0.0.1 \
          -e DB_USER=root \
          -e DB_PASSWORD=admin \
          -e DB_NAME=rbac \
          medivault-app \
          python app.py

    - name: Wait for Flask app to boot
      run: sleep 20

    - name: Test `/` endpoint
      run: curl --fail http://localhost:5000/

    - name: Test `/test-db` endpoint
      run: curl --fail http://localhost:5000/test-db

    - name: Install Chromium and test dependencies
      run: |
        sudo apt update
        sudo apt install -y chromium-browser chromium-chromedriver
        pip install -r backend/requirements.txt

    - name: Run Selenium UI test for /register
      run: python backend/tests/test_register_ui.py
