name: MediVault Dependency Check (Python Audit)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipaudit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit
        run: pip-audit --requirement backend/requirements.txt
