name: OWASP Dependency Check

on:
  push:
    branches: [main]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depcheck_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'medivault'
          path: 'backend'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload DepCheck report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
