name: MediVault TestCases

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  medivault-test-cases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install project dependencies
        run: pip install -r backend/requirements.txt

      - name: Start Flask & MySQL with Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for Flask to start
        run: |
          echo "Waiting for Flask..."
          for i in {1..10}; do
            curl --fail http://localhost:5000/ && echo "✅ Flask is up!" && exit 0
            echo "⏳ Waiting ($i)..."
            sleep 3
          done
          echo "❌ Flask did not start."
          docker-compose logs
          exit 1

      - name: Install Chrome and Selenium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          pip install selenium

      - name: Run Selenium Test
        run: python backend/tests/test_register_ui.py

      - name: Tear down containers
        if: always()
        run: docker-compose down
