name: Docker-Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan for secrets using Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --verbose --redact

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Check that it installed successfully

      # Build the containers
      - name: Build containers
        run: docker-compose -f docker-compose.yml build --parallel

      # Start the services
      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      # Smoke-test the Flask app
      - name: Smoke test Flask
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:5000/; do
            echo "Waiting for Flask…"
            sleep 5
          done
          echo "Flask is responding!"

      # Run the tests
      - name: Run backend tests
        run: docker-compose run --rm flask_app python -m unittest discover

      # Tear down
      - name: Tear down
        run: docker-compose -f docker-compose.yml down --volumes
