name: Flask Docker CI Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: rbac
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20
        ports:
          - 3306:3306

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Flask app Docker image
      working-directory: ./backend
      run: docker build -t medivault-app .

    - name: Run Flask app container
      run: |
        docker run -d --name flask-app \
          --network host \
          -e FLASK_SECRET_KEY=testsecret \
          -e FLASK_ENV=development \
          -e DB_HOST=127.0.0.1 \
          -e DB_USER=root \
          -e DB_PASSWORD=admin \
          -e DB_NAME=rbac \
          medivault-app

    - name: Wait for app to become available
      run: sleep 20

    - name: Test /test-db endpoint
      run: curl --fail http://localhost:5000/test-db
