name: Flask App CI Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: rbac
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt || pip install flask flask-login pymysql python-dotenv

    - name: Run Flask app in background
      working-directory: ./backend
      env:
        FLASK_SECRET_KEY: testsecret
        FLASK_ENV: development
        DB_HOST: mysql             # ✅ Important!
        DB_USER: root
        DB_PASSWORD: admin
        DB_NAME: rbac
      run: |
        python app.py &
        sleep 20

    - name: Test /test-db endpoint
      run: curl --fail http://localhost:5000/test-db
